require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RegimentsController do

  # This should return the minimal set of attributes required to create a valid
  # Regiment. As you add validations to Regiment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all regiments as @regiments" do
      regiment = Regiment.create! valid_attributes
      get :index
      assigns(:regiments).should eq([regiment])
    end
  end

  describe "GET show" do
    it "assigns the requested regiment as @regiment" do
      regiment = Regiment.create! valid_attributes
      get :show, :id => regiment.id.to_s
      assigns(:regiment).should eq(regiment)
    end
  end

  describe "GET new" do
    it "assigns a new regiment as @regiment" do
      get :new
      assigns(:regiment).should be_a_new(Regiment)
    end
  end

  describe "GET edit" do
    it "assigns the requested regiment as @regiment" do
      regiment = Regiment.create! valid_attributes
      get :edit, :id => regiment.id.to_s
      assigns(:regiment).should eq(regiment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Regiment" do
        expect {
          post :create, :regiment => valid_attributes
        }.to change(Regiment, :count).by(1)
      end

      it "assigns a newly created regiment as @regiment" do
        post :create, :regiment => valid_attributes
        assigns(:regiment).should be_a(Regiment)
        assigns(:regiment).should be_persisted
      end

      it "redirects to the created regiment" do
        post :create, :regiment => valid_attributes
        response.should redirect_to(Regiment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved regiment as @regiment" do
        # Trigger the behavior that occurs when invalid params are submitted
        Regiment.any_instance.stub(:save).and_return(false)
        post :create, :regiment => {}
        assigns(:regiment).should be_a_new(Regiment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Regiment.any_instance.stub(:save).and_return(false)
        post :create, :regiment => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested regiment" do
        regiment = Regiment.create! valid_attributes
        # Assuming there are no other regiments in the database, this
        # specifies that the Regiment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Regiment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => regiment.id, :regiment => {'these' => 'params'}
      end

      it "assigns the requested regiment as @regiment" do
        regiment = Regiment.create! valid_attributes
        put :update, :id => regiment.id, :regiment => valid_attributes
        assigns(:regiment).should eq(regiment)
      end

      it "redirects to the regiment" do
        regiment = Regiment.create! valid_attributes
        put :update, :id => regiment.id, :regiment => valid_attributes
        response.should redirect_to(regiment)
      end
    end

    describe "with invalid params" do
      it "assigns the regiment as @regiment" do
        regiment = Regiment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Regiment.any_instance.stub(:save).and_return(false)
        put :update, :id => regiment.id.to_s, :regiment => {}
        assigns(:regiment).should eq(regiment)
      end

      it "re-renders the 'edit' template" do
        regiment = Regiment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Regiment.any_instance.stub(:save).and_return(false)
        put :update, :id => regiment.id.to_s, :regiment => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested regiment" do
      regiment = Regiment.create! valid_attributes
      expect {
        delete :destroy, :id => regiment.id.to_s
      }.to change(Regiment, :count).by(-1)
    end

    it "redirects to the regiments list" do
      regiment = Regiment.create! valid_attributes
      delete :destroy, :id => regiment.id.to_s
      response.should redirect_to(regiments_url)
    end
  end

end
